# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/januaditya/Workspace/_git/up/vehicle-state-estimator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/januaditya/Workspace/_git/up/vehicle-state-estimator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/januaditya/Workspace/_git/up/vehicle-state-estimator/CMakeFiles /Users/januaditya/Workspace/_git/up/vehicle-state-estimator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/januaditya/Workspace/_git/up/vehicle-state-estimator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vehicle-state-estimator

# Build rule for target.
vehicle-state-estimator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vehicle-state-estimator
.PHONY : vehicle-state-estimator

# fast build rule for target.
vehicle-state-estimator/fast:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/build
.PHONY : vehicle-state-estimator/fast

App.o: App.cpp.o
.PHONY : App.o

# target to build an object file
App.cpp.o:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/App.cpp.o
.PHONY : App.cpp.o

App.i: App.cpp.i
.PHONY : App.i

# target to preprocess a source file
App.cpp.i:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/App.cpp.i
.PHONY : App.cpp.i

App.s: App.cpp.s
.PHONY : App.s

# target to generate assembly for a file
App.cpp.s:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/App.cpp.s
.PHONY : App.cpp.s

Gaussian.o: Gaussian.cpp.o
.PHONY : Gaussian.o

# target to build an object file
Gaussian.cpp.o:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Gaussian.cpp.o
.PHONY : Gaussian.cpp.o

Gaussian.i: Gaussian.cpp.i
.PHONY : Gaussian.i

# target to preprocess a source file
Gaussian.cpp.i:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Gaussian.cpp.i
.PHONY : Gaussian.cpp.i

Gaussian.s: Gaussian.cpp.s
.PHONY : Gaussian.s

# target to generate assembly for a file
Gaussian.cpp.s:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Gaussian.cpp.s
.PHONY : Gaussian.cpp.s

Model.o: Model.cpp.o
.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i
.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s
.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Model.cpp.s
.PHONY : Model.cpp.s

Sensor.o: Sensor.cpp.o
.PHONY : Sensor.o

# target to build an object file
Sensor.cpp.o:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Sensor.cpp.o
.PHONY : Sensor.cpp.o

Sensor.i: Sensor.cpp.i
.PHONY : Sensor.i

# target to preprocess a source file
Sensor.cpp.i:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Sensor.cpp.i
.PHONY : Sensor.cpp.i

Sensor.s: Sensor.cpp.s
.PHONY : Sensor.s

# target to generate assembly for a file
Sensor.cpp.s:
	$(MAKE) -f CMakeFiles/vehicle-state-estimator.dir/build.make CMakeFiles/vehicle-state-estimator.dir/Sensor.cpp.s
.PHONY : Sensor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vehicle-state-estimator"
	@echo "... App.o"
	@echo "... App.i"
	@echo "... App.s"
	@echo "... Gaussian.o"
	@echo "... Gaussian.i"
	@echo "... Gaussian.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... Sensor.o"
	@echo "... Sensor.i"
	@echo "... Sensor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

